/*###############################################################
BDS function symbols and RVAs
File generated by BDumper, a rust bds pdb dumper made by Luke7720
###############################################################*/
#pragma once
//?getBlock@BlockSource@@UEBAAEBVBlock@@AEBVBlockPos@@I@Z
//public: virtual Block const& __ptr64 __cdecl BlockSource::getBlock(BlockPos const& __ptr64,unsigned int) const __ptr64
constexpr unsigned int MD5_a18b604630cd5801dc073ccb97e87f96 = 0x1724190;

//?getBlockEntity@BlockSource@@UEBAPEBVBlockActor@@AEBVBlockPos@@@Z
//public: virtual BlockActor const* __ptr64 __cdecl BlockSource::getBlockEntity(BlockPos const const __ptr64)& __ptr64
constexpr unsigned int MD5_0adb196a370e919a5ed2f18aad3074e3 = 0x1724220;

//?getNameTag@Actor@@UEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ
//public: virtual std::basic_string<char, std::char_traits<char>, std::allocator<char>> const& __ptr64 __cdecl Actor::getNameTag(void) const __ptr64
constexpr unsigned int MD5_7044ab83168b0fd345329e6566fd47fd = 0x14b02a0;

//?getId@ItemStackBase@@QEBAFXZ
//public: short __cdecl ItemStackBase::getId(void) const __ptr64
constexpr unsigned int MD5_20bbe6b0f3ccd51bca5e7f128592acaf = 0x1770d30;

//?getName@ItemStackBase@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ
//public: std::basic_string<char, std::char_traits<char>, std::allocator<char>> __cdecl ItemStackBase::getName(void) const __ptr64
constexpr unsigned int MD5_6d581a35d7ad70fd364b60c3ebe93394 = 0x1771ab0;

//?isExpanded@PistonBlockActor@@QEBA_NXZ
//public: bool __cdecl PistonBlockActor::isExpanded(void) const __ptr64
constexpr unsigned int MD5_1dd8d8ed460b0060fefa6edd99883d5d = 0x1c752f0;

//?isRetracting@PistonBlockActor@@QEBA_NXZ
//public: bool __cdecl PistonBlockActor::isRetracting(void) const __ptr64
constexpr unsigned int MD5_a98435288228c1d7b6dad513eaecdb78 = 0x1c754a0;

//?canSurvive@PistonBlock@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@@Z
//public: virtual bool __cdecl PistonBlock::canSurvive(BlockSource& __ptr64, BlockPos const const __ptr64)& __ptr64
constexpr unsigned int MD5_52ca93bd7ea30062b1258c8d2c9d842f = 0x212c160;

//?isExpanding@PistonBlockActor@@QEBA_NXZ
//public: bool __cdecl PistonBlockActor::isExpanding(void) const __ptr64
constexpr unsigned int MD5_1a3dadff7530cb78717ef6ade0566ab1 = 0x1c75310;

//?isMoving@PistonBlockActor@@QEBA_NXZ
//public: bool __cdecl PistonBlockActor::isMoving(void) const __ptr64
constexpr unsigned int MD5_8ea3c476e8f3596d47f45dcc40e7e5ce = 0x1c753d0;

//?_hasBlockAttached@PistonBlockActor@@AEAA_NAEBVBlockPos@@@Z
//private: bool __cdecl PistonBlockActor::_hasBlockAttached(BlockPos const& __ptr64) __ptr64
constexpr unsigned int MD5_6f6187f91ebfd7ac5108b1391acfd722 = 0x1c6cd30;

//?_checkAttachedBlocks@PistonBlockActor@@AEAA_NAEAVBlockSource@@@Z
//private: bool __cdecl PistonBlockActor::_checkAttachedBlocks(BlockSource& __ptr64) __ptr64
constexpr unsigned int MD5_d7a00ac2d9adec414a3662b847fe2d7c = 0x1c6b3e0;