/*###############################################################
BDS function symbols and RVAs
File generated by BDumper, a rust bds pdb dumper made by Luke7720
###############################################################*/
#pragma once
//?getBlock@BlockSource@@UEBAAEBVBlock@@AEBVBlockPos@@@Z
//public: virtual Block const& __cdecl BlockSource::getBlock(BlockPos const&) const
constexpr unsigned int MD5_b39e5e5d8d859123e0149e23a9a7460b = 0xfaa0b0;

//?getBlockEntity@BlockSource@@QEAAPEAVBlockActor@@AEBVBlockPos@@@Z
//public: BlockActor* __cdecl BlockSource::getBlockEntity(BlockPos const&)
constexpr unsigned int MD5_638cb3beca85bc61a794f129df3ea53f = 0xfaa1b0;

//?getPos@Actor@@UEBAAEBVVec3@@XZ
//public: virtual Vec3 const& __cdecl Actor::getPos(void) const
constexpr unsigned int MD5_cecb628ba58436266fb3ca43d5d88fdc = 0xb41ff0;

//?getNameTag@Actor@@UEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ
//public: virtual std::basic_string<char, std::char_traits<char>, std::allocator<char>> const& __cdecl Actor::getNameTag(void) const
constexpr unsigned int MD5_7044ab83168b0fd345329e6566fd47fd = 0xb41ad0;

//?getId@ItemStackBase@@QEBAFXZ
//public: short __cdecl ItemStackBase::getId(void) const
constexpr unsigned int MD5_20bbe6b0f3ccd51bca5e7f128592acaf = 0xc8c120;

//?getName@ItemStackBase@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ
//public: std::basic_string<char, std::char_traits<char>, std::allocator<char>> __cdecl ItemStackBase::getName(void) const
constexpr unsigned int MD5_6d581a35d7ad70fd364b60c3ebe93394 = 0xc8c830;

//?isExpanded@PistonBlockActor@@QEBA_NXZ
//public: bool __cdecl PistonBlockActor::isExpanded(void) const
constexpr unsigned int MD5_1dd8d8ed460b0060fefa6edd99883d5d = 0x1260f80;

//?isRetracting@PistonBlockActor@@QEBA_NXZ
//public: bool __cdecl PistonBlockActor::isRetracting(void) const
constexpr unsigned int MD5_a98435288228c1d7b6dad513eaecdb78 = 0x12610b0;

//?canSurvive@PistonBlock@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@@Z
//public: virtual bool __cdecl PistonBlock::canSurvive(BlockSource&, BlockPos const&) const
constexpr unsigned int MD5_52ca93bd7ea30062b1258c8d2c9d842f = 0x1277c20;

//?isExpanding@PistonBlockActor@@QEBA_NXZ
//public: bool __cdecl PistonBlockActor::isExpanding(void) const
constexpr unsigned int MD5_1a3dadff7530cb78717ef6ade0566ab1 = 0x1260fa0;

//?isMoving@PistonBlockActor@@QEBA_NXZ
//public: bool __cdecl PistonBlockActor::isMoving(void) const
constexpr unsigned int MD5_8ea3c476e8f3596d47f45dcc40e7e5ce = 0x1261050;

//?_hasBlockAttached@PistonBlockActor@@AEAA_NAEBVBlockPos@@@Z
//private: bool __cdecl PistonBlockActor::_hasBlockAttached(BlockPos const&)
constexpr unsigned int MD5_6f6187f91ebfd7ac5108b1391acfd722 = 0x1259ec0;